language: php
php:
  - 7.0

sudo: false

env:
  global:
  matrix:

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version

install:
  # composer install should fail on bad patches.
  - export COMPOSER_EXIT_ON_PATCH_FAILURE=1
  - composer --verbose install

notifications:
  email: false
